spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dm
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /documentacao
  api-docs:
    path: /api-docs