spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  flyway:
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /documentacao
  api-docs:
    path: /api-docs
